In [1]:
# ==============================
# 1. IMPORTAR LIBRERIAS
# ==============================

import pandas as pd
import numpy as np
 
# Configuracion de visualizacion de dataframes

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.float_format", "{:.2f}".format)
 
# Ignorar warnings
# ==============================================================================
import warnings
warnings.filterwarnings("ignore")

In [2]:
# ==============================
# 2. CARGAR DATASETS
# ==============================

# Rutas de los archivos
ruta_bank = "../datos/datos_brutos/bank-additional.csv"
ruta_customer = "../datos/datos_brutos/customer-details.xlsx"

In [3]:
# Cargar dataset bancario
df_bank = pd.read_csv(ruta_bank)

# Eliminar columnas basura tipo "Unnamed"
df_bank = df_bank.loc[:, ~df_bank.columns.str.contains("^Unnamed")]

# Visualizar primeras filas
df_bank.head()

,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,id_
0,NaN,housemaid,MARRIED,basic.4y,0.00,0.00,0.00,telephone,261,1,999,0,NONEXISTENT,1.10,"93,994","-36,4","4,857",5191,no,2-agosto-2019,41.49,-71.23,089b39d8-e4d0-461b-87d4-814d71e0e079
1,57.00,services,MARRIED,high.school,NaN,0.00,0.00,telephone,149,1,999,0,NONEXISTENT,1.10,"93,994","-36,4",NaN,5191,no,14-septiembre-2016,34.60,-83.92,e9d37224-cb6f-4942-98d7-46672963d097
2,37.00,services,MARRIED,high.school,0.00,1.00,0.00,telephone,226,1,999,0,NONEXISTENT,1.10,"93,994","-36,4","4,857",5191,no,15-febrero-2019,34.94,-94.85,3f9f49b5-e410-4948-bf6e-f9244f04918b
3,40.00,admin.,MARRIED,basic.6y,0.00,0.00,0.00,telephone,151,1,999,0,NONEXISTENT,1.10,"93,994","-36,4",NaN,5191,no,29-noviembre-2015,49.04,-70.31,9991fafb-4447-451a-8be2-b0df6098d13e
4,56.00,services,MARRIED,high.school,0.00,0.00,1.00,telephone,307,1,999,0,NONEXISTENT,1.10,"93,994","-36,4",NaN,5191,no,29-enero-2017,38.03,-104.46,eca60b76-70b6-4077-80ba-bc52e8ebb0eb

In [4]:
# Cargar todas las hojas del Excel
excel_customer = pd.read_excel(
    ruta_customer,
    sheet_name=None
)

In [5]:
# Unir todas las hojas del Excel
df_customer = pd.concat(
    excel_customer.values(),
    ignore_index=True
)

In [6]:
# Eliminar columnas basura tipo "Unnamed"
df_customer = df_customer.loc[
    :,
    ~df_customer.columns.str.contains("^Unnamed")
]

In [7]:
df_customer.head()

,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
0,161770,1,0,2012-04-04,29,089b39d8-e4d0-461b-87d4-814d71e0e079
1,85477,1,1,2012-12-30,7,e9d37224-cb6f-4942-98d7-46672963d097
2,147233,1,1,2012-02-02,5,3f9f49b5-e410-4948-bf6e-f9244f04918b
3,121393,1,2,2012-12-21,29,9991fafb-4447-451a-8be2-b0df6098d13e
4,63164,1,2,2012-06-20,20,eca60b76-70b6-4077-80ba-bc52e8ebb0eb

In [8]:
print("Shape df_bank:", df_bank.shape)
print("Shape df_customer:", df_customer.shape)

Shape df_bank: (43000, 23)
Shape df_customer: (43170, 6)

In [9]:
# ==============================
# 3. REVISION DE TIPOS DE DATOS
# ==============================

print("Tipos de datos de df_bank:")
display(df_bank.dtypes)

print("\nTipos de datos de df_customer:")
display(df_customer.dtypes)

Tipos de datos de df_bank:

age               float64
job                object
marital            object
education          object
default           float64
housing           float64
loan              float64
contact            object
duration            int64
campaign            int64
pdays               int64
previous            int64
poutcome           object
emp.var.rate      float64
cons.price.idx     object
cons.conf.idx      object
euribor3m          object
nr.employed        object
y                  object
date               object
latitude          float64
longitude         float64
id_                object
dtype: object

Tipos de datos de df_customer:

Income                        int64
Kidhome                       int64
Teenhome                      int64
Dt_Customer          datetime64[ns]
NumWebVisitsMonth             int64
ID                           object
dtype: object

In [10]:
# Informacion general de df_bank
df_bank.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43000 entries, 0 to 42999
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             37880 non-null  float64
 1   job             42655 non-null  object
 2   marital         42915 non-null  object
 3   education       41193 non-null  object
 4   default         34019 non-null  float64
 5   housing         41974 non-null  float64
 6   loan            41974 non-null  float64
 7   contact         43000 non-null  object
 8   duration        43000 non-null  int64
 9   campaign        43000 non-null  int64
 10  pdays           43000 non-null  int64
 11  previous        43000 non-null  int64
 12  poutcome        43000 non-null  object
 13  emp.var.rate    43000 non-null  float64
 14  cons.price.idx  42529 non-null  object
 15  cons.conf.idx   43000 non-null  object
 16  euribor3m       33744 non-null  object
 17  nr.employed     43000 non-null  object
 18  y               43000 non-null  object
 19  date            42752 non-null  object
 20  latitude        43000 non-null  float64
 21  longitude       43000 non-null  float64
 22  id_             43000 non-null  object
dtypes: float64(7), int64(4), object(12)
memory usage: 7.5+ MB

In [11]:
# Informacion general de df_customer
df_customer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43170 entries, 0 to 43169
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Income             43170 non-null  int64
 1   Kidhome            43170 non-null  int64
 2   Teenhome           43170 non-null  int64
 3   Dt_Customer        43170 non-null  datetime64[ns]
 4   NumWebVisitsMonth  43170 non-null  int64
 5   ID                 43170 non-null  object
dtypes: datetime64[ns](1), int64(4), object(1)
memory usage: 2.0+ MB

In [12]:
# Columnas numericas y categoricas de df_bank

columnas_numericas_bank = df_bank.select_dtypes(include=["int64", "float64"]).columns
columnas_categoricas_bank = df_bank.select_dtypes(include=["object"]).columns

print("Columnas numericas df_bank:")
print(columnas_numericas_bank)

print("\nColumnas categoricas df_bank:")
print(columnas_categoricas_bank)

Columnas numericas df_bank:
Index(['age', 'default', 'housing', 'loan', 'duration', 'campaign', 'pdays',
       'previous', 'emp.var.rate', 'latitude', 'longitude'],
      dtype='object')

Columnas categoricas df_bank:
Index(['job', 'marital', 'education', 'contact', 'poutcome', 'cons.price.idx',
       'cons.conf.idx', 'euribor3m', 'nr.employed', 'y', 'date', 'id_'],
      dtype='object')

In [13]:
# Columnas numericas y categoricas de df_customer

columnas_numericas_customer = df_customer.select_dtypes(include=["int64", "float64"]).columns
columnas_categoricas_customer = df_customer.select_dtypes(include=["object"]).columns

print("Columnas numericas df_customer:")
print(columnas_numericas_customer)

print("\nColumnas categoricas df_customer:")
print(columnas_categoricas_customer)

Columnas numericas df_customer:
Index(['Income', 'Kidhome', 'Teenhome', 'NumWebVisitsMonth'], dtype='object')

Columnas categoricas df_customer:
Index(['ID'], dtype='object')

In [14]:
# Revision de columnas que deberian ser fecha o numericas

columnas_revision_bank = [
    "date",
    "cons.price.idx",
    "cons.conf.idx",
    "euribor3m"
]

for columna in columnas_revision_bank:
    print(f"\nColumna: {columna}")
    print("Tipo:", df_bank[columna].dtype)
    print(df_bank[columna].head())

Columna: date
Tipo: object
0         2-agosto-2019
1    14-septiembre-2016
2       15-febrero-2019
3     29-noviembre-2015
4         29-enero-2017
Name: date, dtype: object

Columna: cons.price.idx
Tipo: object
0    93,994
1    93,994
2    93,994
3    93,994
4    93,994
Name: cons.price.idx, dtype: object

Columna: cons.conf.idx
Tipo: object
0    -36,4
1    -36,4
2    -36,4
3    -36,4
4    -36,4
Name: cons.conf.idx, dtype: object

Columna: euribor3m
Tipo: object
0    4,857
1      NaN
2    4,857
3      NaN
4      NaN
Name: euribor3m, dtype: object

In [15]:
# Revision de columnas de fecha en df_customer

columnas_revision_customer = [
    "Dt_Customer"
]

for columna in columnas_revision_customer:
    print(f"\nColumna: {columna}")
    print("Tipo:", df_customer[columna].dtype)
    print(df_customer[columna].head())

Columna: Dt_Customer
Tipo: datetime64[ns]
0   2012-04-04
1   2012-12-30
2   2012-02-02
3   2012-12-21
4   2012-06-20
Name: Dt_Customer, dtype: datetime64[ns]

In [16]:
# Resumen inicial de tipos

print("Resumen de tipos:")
print(f"df_bank tiene {len(columnas_numericas_bank)} columnas numericas.")
print(f"df_bank tiene {len(columnas_categoricas_bank)} columnas categoricas.")
print(f"df_customer tiene {len(columnas_numericas_customer)} columnas numericas.")
print(f"df_customer tiene {len(columnas_categoricas_customer)} columnas categoricas.")

Resumen de tipos:
df_bank tiene 11 columnas numericas.
df_bank tiene 12 columnas categoricas.
df_customer tiene 4 columnas numericas.
df_customer tiene 1 columnas categoricas.

In [17]:
# ==============================
# 4. LIMPIEZA DE COLUMNAS NUMERICAS
# ==============================

# Columnas numericas mal interpretadas como object
columnas_numericas_texto = [
    "cons.price.idx",
    "cons.conf.idx",
    "euribor3m",
    "nr.employed"
]

In [18]:
def limpiar_columnas_numericas(df, columnas):
    """
    Limpia columnas numéricas que contienen comas decimales y las convierte
    al tipo numérico float.

    Parámetros
    ----------
    df : pandas.DataFrame
        DataFrame que contiene las columnas a limpiar.

    columnas : list
        Lista de columnas que deben convertirse a formato numérico.

    Retorna
    -------
    pandas.DataFrame
        DataFrame con las columnas convertidas a tipo numérico.
    """

    df = df.copy()

    for columna in columnas:

        # Reemplazar comas por puntos
        df[columna] = (
            df[columna]
            .astype(str)
            .str.replace(",", ".", regex=False)
        )

        # Convertir a numérico
        df[columna] = pd.to_numeric(
            df[columna],
            errors="coerce"
        )

    return df

In [19]:
# ==============================
# APLICAR FUNCION DE LIMPIEZA
# ==============================
# Se aplica la función sobre las columnas numéricas
# detectadas anteriormente.

df_bank = limpiar_columnas_numericas(
    df_bank,
    columnas_numericas_texto
)

In [20]:
# ==============================
# VERIFICAR TIPOS DE DATOS
# ==============================
# Comprobamos que las columnas ahora sean numéricas.

df_bank[
    [
        "cons.price.idx",
        "cons.conf.idx",
        "euribor3m",
        "nr.employed"
    ]
].dtypes

cons.price.idx    float64
cons.conf.idx     float64
euribor3m         float64
nr.employed       float64
dtype: object

In [21]:
# Revisaión de valores nulos en las columnas numéricas limpiadas
  
df_bank[
    [
        "cons.price.idx",
        "cons.conf.idx",
        "euribor3m",
        "nr.employed"
    ]
].isnull().sum()

cons.price.idx     471
cons.conf.idx        0
euribor3m         9256
nr.employed          0
dtype: int64

In [22]:
df_bank.head()

,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,id_
0,NaN,housemaid,MARRIED,basic.4y,0.00,0.00,0.00,telephone,261,1,999,0,NONEXISTENT,1.10,93.99,-36.40,4.86,5191.00,no,2-agosto-2019,41.49,-71.23,089b39d8-e4d0-461b-87d4-814d71e0e079
1,57.00,services,MARRIED,high.school,NaN,0.00,0.00,telephone,149,1,999,0,NONEXISTENT,1.10,93.99,-36.40,NaN,5191.00,no,14-septiembre-2016,34.60,-83.92,e9d37224-cb6f-4942-98d7-46672963d097
2,37.00,services,MARRIED,high.school,0.00,1.00,0.00,telephone,226,1,999,0,NONEXISTENT,1.10,93.99,-36.40,4.86,5191.00,no,15-febrero-2019,34.94,-94.85,3f9f49b5-e410-4948-bf6e-f9244f04918b
3,40.00,admin.,MARRIED,basic.6y,0.00,0.00,0.00,telephone,151,1,999,0,NONEXISTENT,1.10,93.99,-36.40,NaN,5191.00,no,29-noviembre-2015,49.04,-70.31,9991fafb-4447-451a-8be2-b0df6098d13e
4,56.00,services,MARRIED,high.school,0.00,0.00,1.00,telephone,307,1,999,0,NONEXISTENT,1.10,93.99,-36.40,NaN,5191.00,no,29-enero-2017,38.03,-104.46,eca60b76-70b6-4077-80ba-bc52e8ebb0eb

In [23]:
# ==============================
# 5. LIMPIEZA DE COLUMNAS BINARIAS
# ==============================
# En este bloque se transforman variables binarias
# codificadas numericamente en categorias interpretables.
# Esto mejora la legibilidad y facilita el analisis exploratorio.

In [24]:
# ==============================
# 5.1 REVISION DE VARIABLES BINARIAS
# ==============================
# Se revisan los valores unicos de las variables binarias
# antes de realizar la conversion.

print(df_bank["default"].value_counts(dropna=False))

print(df_bank["housing"].value_counts(dropna=False))

print(df_bank["loan"].value_counts(dropna=False))

default
0.00    34016
NaN      8981
1.00        3
Name: count, dtype: int64
housing
1.00    22498
0.00    19476
NaN      1026
Name: count, dtype: int64
loan
0.00    35442
1.00     6532
NaN      1026
Name: count, dtype: int64

In [25]:
# ==============================
# 5.2 DEFINICION DE COLUMNAS BINARIAS
# ==============================
# Se almacenan las variables binarias
# que seran transformadas.

columnas_binarias = [
    "default",
    "housing",
    "loan"
]

In [26]:
# ==============================
# 5.3 FUNCION PARA CONVERTIR VARIABLES BINARIAS
# ==============================
# Esta funcion transforma variables binarias
# codificadas como 0 y 1 en categorias
# interpretables "No" y "Yes".

def convertir_binarias(df, columnas):
    """
    Convierte variables binarias numericas
    en categorias de texto.

    Parametros
    ----------
    df : pandas.DataFrame
        DataFrame que contiene las columnas binarias.

    columnas : list
        Lista de columnas binarias a convertir.

    Retorna
    -------
    pandas.DataFrame
        DataFrame con las variables binarias convertidas.
    """

    df = df.copy()

    mapa = {
        1.0: "Yes",
        0.0: "No"
    }

    for columna in columnas:

        df[columna] = df[columna].map(mapa)

    return df

In [27]:
# ==============================
# 5.4 APLICAR CONVERSION DE VARIABLES BINARIAS
# ==============================
# Se aplica la conversion de variables binarias
# para mejorar la interpretabilidad del dataset.

df_bank = convertir_binarias(
    df_bank,
    columnas_binarias
)

In [28]:
# ==============================
# 5.5 VERIFICACION DE LA CONVERSION
# ==============================
# Se revisan nuevamente los valores unicos
# tras la conversion de las variables binarias.

print(df_bank["default"].value_counts(dropna=False))

print(df_bank["housing"].value_counts(dropna=False))

print(df_bank["loan"].value_counts(dropna=False))

default
No     34016
NaN     8981
Yes        3
Name: count, dtype: int64
housing
Yes    22498
No     19476
NaN     1026
Name: count, dtype: int64
loan
No     35442
Yes     6532
NaN     1026
Name: count, dtype: int64

In [29]:
# ==============================
# 5.6 REVISION FINAL DE TIPOS
# ==============================
# Se comprueba el tipo de dato actual
# de las variables binarias tras la conversion.

df_bank[
    [
        "default",
        "housing",
        "loan"
    ]
].dtypes

default    object
housing    object
loan       object
dtype: object

In [30]:
# ==============================
# 6. LIMPIEZA DE FECHAS
# ==============================
# En este bloque se revisa la columna date y se valida
# que tenga correctamente formato datetime para permitir
# futuros analisis temporales.

In [31]:
# ==============================
# 6.1 REVISION INICIAL DE LA COLUMNA DATE
# ==============================
# Visualizamos algunos ejemplos de la columna date
# para entender su estructura antes de limpiarla.

df_bank["date"].head(10)

0         2-agosto-2019
1    14-septiembre-2016
2       15-febrero-2019
3     29-noviembre-2015
4         29-enero-2017
5    26-septiembre-2015
6         25-enero-2019
7    25-septiembre-2017
8         18-enero-2018
9      2-noviembre-2016
Name: date, dtype: object

In [32]:
# ==============================
# 6.2 DICCIONARIO DE MESES EN ESPAÑOL
# ==============================
# Este diccionario servirá para reemplazar
# los nombres de los meses en español por inglés,
# permitiendo que pandas pueda interpretar las fechas.

meses_es_en = {
    "enero": "January",
    "febrero": "February",
    "marzo": "March",
    "abril": "April",
    "mayo": "May",
    "junio": "June",
    "julio": "July",
    "agosto": "August",
    "septiembre": "September",
    "octubre": "October",
    "noviembre": "November",
    "diciembre": "December"
}

In [33]:
# ==============================
# 6.3 FUNCION PARA LIMPIAR FECHAS EN ESPAÑOL
# ==============================
# Esta función reemplaza los meses en español
# por meses en inglés y convierte la columna
# al tipo datetime.

def limpiar_fechas_espanol(df, columna):
    """
    Limpia una columna de fechas que contiene meses en español
    y la convierte al tipo datetime.

    Parámetros
    ----------
    df : pandas.DataFrame
        DataFrame que contiene la columna de fechas.

    columna : str
        Nombre de la columna que contiene las fechas.

    Retorna
    -------
    pandas.DataFrame
        DataFrame con la columna convertida a datetime.
    """

    df = df.copy()

    # Convertir a string
    df[columna] = df[columna].astype(str)

    # Reemplazar meses en español por inglés
    for mes_es, mes_en in meses_es_en.items():

        df[columna] = df[columna].str.replace(
            mes_es,
            mes_en,
            regex=False
        )

    # Convertir a datetime
    df[columna] = pd.to_datetime(
        df[columna],
        errors="coerce"
    )

    return df

In [34]:
# ==============================
# 6.4 APLICAR FUNCION DE LIMPIEZA DE FECHAS
# ==============================
# Se transforma la columna date al formato datetime.

df_bank = limpiar_fechas_espanol(
    df_bank,
    "date"
)

In [35]:
# ==============================
# 6.5 VERIFICAR CONVERSION DE FECHAS
# ==============================
# Comprobamos que la columna date ahora
# tenga tipo datetime.

df_bank["date"].dtype

dtype('<M8[ns]')

In [36]:
# ==============================
# 6.6 VISUALIZAR RESULTADO FINAL
# ==============================
# Mostramos algunos registros para verificar
# que las fechas se han convertido correctamente.

df_bank["date"].head(10)

0   2019-08-02
1   2016-09-14
2   2019-02-15
3   2015-11-29
4   2017-01-29
5   2015-09-26
6   2019-01-25
7   2017-09-25
8   2018-01-18
9   2016-11-02
Name: date, dtype: datetime64[ns]

In [37]:
# ==============================
# 6.7 REVISION DE NULOS EN DATE
# ==============================
# Comprobamos si algunas fechas no pudieron
# convertirse correctamente.

df_bank["date"].isnull().sum()

np.int64(248)

In [38]:
# ==============================
# 7. LIMPIEZA Y TRATAMIENTO DE NULOS
# ==============================
# En este bloque se revisan e imputan los valores nulos
# de las variables numericas y categoricas del dataset.

In [39]:
# ==============================
# 7.1 REVISION DE VALORES NULOS
# ==============================
# Se calcula el numero y porcentaje de nulos
# presentes en cada columna de df_bank.

nulos_bank = df_bank.isnull().sum()
porcentaje_nulos_bank = (df_bank.isnull().sum() / len(df_bank) * 100).round(2)

resumen_nulos_bank = pd.DataFrame({
    "nulos": nulos_bank,
    "porcentaje": porcentaje_nulos_bank
})

resumen_nulos_bank = resumen_nulos_bank[resumen_nulos_bank["nulos"] > 0]

resumen_nulos_bank.sort_values(by="porcentaje", ascending=False)

                nulos  porcentaje
euribor3m        9256       21.53
default          8981       20.89
age              5120       11.91
education        1807        4.20
loan             1026        2.39
housing          1026        2.39
cons.price.idx    471        1.10
job               345        0.80
date              248        0.58
marital            85        0.20

In [40]:
# ==============================
# 7.1 REVISION DE VALORES NULOS
# ==============================
# Se calcula el numero y porcentaje de nulos
# presentes en cada columna de df_customer.

nulos_customer = df_customer.isnull().sum()
porcentaje_nulos_customer = (df_customer.isnull().sum() / len(df_customer) * 100).round(2)

resumen_nulos_customer = pd.DataFrame({
    "nulos": nulos_customer,
    "porcentaje": porcentaje_nulos_customer
})

resumen_nulos_customer = resumen_nulos_customer[resumen_nulos_customer["nulos"] > 0]

resumen_nulos_customer.sort_values(by="porcentaje", ascending=False)

Empty DataFrame
Columns: [nulos, porcentaje]
Index: []

In [41]:
df_bank.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43000 entries, 0 to 42999
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             37880 non-null  float64
 1   job             42655 non-null  object
 2   marital         42915 non-null  object
 3   education       41193 non-null  object
 4   default         34019 non-null  object
 5   housing         41974 non-null  object
 6   loan            41974 non-null  object
 7   contact         43000 non-null  object
 8   duration        43000 non-null  int64
 9   campaign        43000 non-null  int64
 10  pdays           43000 non-null  int64
 11  previous        43000 non-null  int64
 12  poutcome        43000 non-null  object
 13  emp.var.rate    43000 non-null  float64
 14  cons.price.idx  42529 non-null  float64
 15  cons.conf.idx   43000 non-null  float64
 16  euribor3m       33744 non-null  float64
 17  nr.employed     43000 non-null  float64
 18  y               43000 non-null  object
 19  date            42752 non-null  datetime64[ns]
 20  latitude        43000 non-null  float64
 21  longitude       43000 non-null  float64
 22  id_             43000 non-null  object
dtypes: datetime64[ns](1), float64(8), int64(4), object(10)
memory usage: 7.5+ MB

In [42]:
# ==============================
# 7.2 FUNCION PARA IMPUTAR NULOS NUMERICOS
# ==============================
# Esta funcion sustituye los valores nulos de columnas numericas
# por la mediana de cada columna.
# Se usa la mediana porque es menos sensible a valores extremos
# que la media y representa mejor el centro de distribuciones sesgadas.

def imputar_nulos_mediana(df, columnas):
    """
    Imputa valores nulos en columnas numericas usando la mediana.

    Parametros
    ----------
    df : pandas.DataFrame
        DataFrame que contiene las columnas a imputar.

    columnas : list
        Lista de columnas numericas en las que se sustituiran los nulos.

    Retorna
    -------
    pandas.DataFrame
        DataFrame con los valores nulos imputados por la mediana.
    """

    df = df.copy()

    for columna in columnas:

        mediana = df[columna].median()

        df[columna] = df[columna].fillna(mediana)

    return df

In [43]:
# ==============================
# 7.3 FUNCION PARA IMPUTAR NULOS CATEGORICOS
# ==============================
# Esta funcion sustituye los valores nulos de columnas categoricas
# por la etiqueta "unknown".
# Se usa "unknown" porque en variables categoricas el valor nulo
# puede representar informacion desconocida o no registrada.
# De esta forma evitamos inventar una categoria usando la moda.

def imputar_nulos_unknown(df, columnas):
    """
    Imputa valores nulos en columnas categoricas usando la etiqueta "unknown".

    Parametros
    ----------
    df : pandas.DataFrame
        DataFrame que contiene las columnas a imputar.

    columnas : list
        Lista de columnas categoricas en las que se sustituiran los nulos.

    Retorna
    -------
    pandas.DataFrame
        DataFrame con los valores nulos imputados como "unknown".
    """

    df = df.copy()

    for columna in columnas:

        df[columna] = df[columna].fillna("unknown")

    return df

In [44]:
# ==============================
# 7.4 FUNCION PARA IMPUTAR NULOS CON MODA
# ==============================
# Esta funcion sustituye los valores nulos por el valor mas frecuente
# de cada columna.
# Se puede usar en variables categoricas binarias cuando tiene sentido
# mantener el comportamiento predominante del dataset.

def imputar_nulos_moda(df, columnas):
    """
    Imputa valores nulos usando la moda de cada columna.

    Parametros
    ----------
    df : pandas.DataFrame
        DataFrame que contiene las columnas a imputar.

    columnas : list
        Lista de columnas en las que se sustituiran los valores nulos.

    Retorna
    -------
    pandas.DataFrame
        DataFrame con los valores nulos imputados por la moda.
    """

    df = df.copy()

    for columna in columnas:

        moda = df[columna].mode()[0]

        df[columna] = df[columna].fillna(moda)

    return df

In [45]:
# ==============================
# 7.5 IMPUTACION NUMERICA
# ==============================
# Se imputan con la mediana las variables numericas con valores nulos.
# La mediana se utiliza porque es menos sensible a valores extremos
# que la media.

columnas_nulos_numericas = [
    "age",
    "cons.price.idx",
    "euribor3m"
]

df_bank = imputar_nulos_mediana(
    df_bank,
    columnas_nulos_numericas
)

In [46]:
# ==============================
# 7.6 IMPUTACION CATEGORICA CON UNKNOWN
# ==============================
# Se imputan con "unknown" las variables categoricas donde el valor
# faltante puede interpretarse como informacion desconocida
# o no registrada.

columnas_nulos_unknown = [
    "job",
    "marital",
    "education",
    "default"
]

df_bank = imputar_nulos_unknown(
    df_bank,
    columnas_nulos_unknown
)

In [47]:
# ==============================
# 7.7 IMPUTACION DE VARIABLES BINARIAS CON MODA
# ==============================
# Se imputan con la moda las variables binarias housing y loan.
# Al tener un porcentaje bajo de nulos, se usa el valor mas frecuente
# como representacion del comportamiento predominante.

columnas_nulos_moda = [
    "housing",
    "loan"
]

df_bank = imputar_nulos_moda(
    df_bank,
    columnas_nulos_moda
)

In [48]:
# ==============================
# 7.8 ELIMINACION DE NULOS EN DATE
# ==============================
# Se eliminan los registros donde date es nulo.
# La decision se justifica porque el porcentaje de nulos es muy bajo
# y crear una fecha artificial podria alterar el analisis temporal.

df_bank = df_bank.dropna(
    subset=["date"]
)

In [49]:
# ==============================
# 7.9 CONVERSION DE AGE A ENTERO
# ==============================
# Tras imputar los valores nulos, la variable age se convierte a entero
# porque representa edad y no valores decimales.

df_bank["age"] = (
    df_bank["age"]
    .round()
    .astype(int)
)

In [50]:
# ==============================
# 7.10 CONVERSION DE NR. EMPLOYED A ENTERO
# ==============================
# Tras imputar los valores nulos, la variable nr. employed se convierte a entero
# porque representa número de empleados y no valores decimales.

df_bank["nr.employed"] = (
    df_bank["nr.employed"]
    .round()
    .astype(int)
)

In [51]:
# ==============================
# 7.11 VERIFICACION FINAL DE NULOS
# ==============================
# Se revisa si despues del tratamiento siguen existiendo valores nulos.

df_bank.isnull().sum().sort_values(ascending=False)

age               0
job               0
marital           0
education         0
default           0
housing           0
loan              0
contact           0
duration          0
campaign          0
pdays             0
previous          0
poutcome          0
emp.var.rate      0
cons.price.idx    0
cons.conf.idx     0
euribor3m         0
nr.employed       0
y                 0
date              0
latitude          0
longitude         0
id_               0
dtype: int64

In [52]:
# ==============================
# 7.12 REVISION FINAL DE TIPOS
# ==============================
# Se revisan los tipos de datos despues de la imputacion
# y conversion de variables.

df_bank.info()

<class 'pandas.core.frame.DataFrame'>
Index: 42752 entries, 0 to 42999
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             42752 non-null  int64
 1   job             42752 non-null  object
 2   marital         42752 non-null  object
 3   education       42752 non-null  object
 4   default         42752 non-null  object
 5   housing         42752 non-null  object
 6   loan            42752 non-null  object
 7   contact         42752 non-null  object
 8   duration        42752 non-null  int64
 9   campaign        42752 non-null  int64
 10  pdays           42752 non-null  int64
 11  previous        42752 non-null  int64
 12  poutcome        42752 non-null  object
 13  emp.var.rate    42752 non-null  float64
 14  cons.price.idx  42752 non-null  float64
 15  cons.conf.idx   42752 non-null  float64
 16  euribor3m       42752 non-null  float64
 17  nr.employed     42752 non-null  int64
 18  y               42752 non-null  object
 19  date            42752 non-null  datetime64[ns]
 20  latitude        42752 non-null  float64
 21  longitude       42752 non-null  float64
 22  id_             42752 non-null  object
dtypes: datetime64[ns](1), float64(6), int64(6), object(10)
memory usage: 7.8+ MB

In [53]:
df_bank.head()

,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,id_
0,38,housemaid,MARRIED,basic.4y,No,No,No,telephone,261,1,999,0,NONEXISTENT,1.10,93.99,-36.40,4.86,5191,no,2019-08-02,41.49,-71.23,089b39d8-e4d0-461b-87d4-814d71e0e079
1,57,services,MARRIED,high.school,unknown,No,No,telephone,149,1,999,0,NONEXISTENT,1.10,93.99,-36.40,4.86,5191,no,2016-09-14,34.60,-83.92,e9d37224-cb6f-4942-98d7-46672963d097
2,37,services,MARRIED,high.school,No,Yes,No,telephone,226,1,999,0,NONEXISTENT,1.10,93.99,-36.40,4.86,5191,no,2019-02-15,34.94,-94.85,3f9f49b5-e410-4948-bf6e-f9244f04918b
3,40,admin.,MARRIED,basic.6y,No,No,No,telephone,151,1,999,0,NONEXISTENT,1.10,93.99,-36.40,4.86,5191,no,2015-11-29,49.04,-70.31,9991fafb-4447-451a-8be2-b0df6098d13e
4,56,services,MARRIED,high.school,No,No,Yes,telephone,307,1,999,0,NONEXISTENT,1.10,93.99,-36.40,4.86,5191,no,2017-01-29,38.03,-104.46,eca60b76-70b6-4077-80ba-bc52e8ebb0eb

In [54]:
# ==============================
# 7.13 REINICIAR INDICE DEL DATASET
# ==============================
# Tras eliminar registros con valores nulos en date,
# se reinicia el indice para mantener una secuencia ordenada.

df_bank = df_bank.reset_index(drop=True)

In [55]:
df_bank.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42752 entries, 0 to 42751
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             42752 non-null  int64
 1   job             42752 non-null  object
 2   marital         42752 non-null  object
 3   education       42752 non-null  object
 4   default         42752 non-null  object
 5   housing         42752 non-null  object
 6   loan            42752 non-null  object
 7   contact         42752 non-null  object
 8   duration        42752 non-null  int64
 9   campaign        42752 non-null  int64
 10  pdays           42752 non-null  int64
 11  previous        42752 non-null  int64
 12  poutcome        42752 non-null  object
 13  emp.var.rate    42752 non-null  float64
 14  cons.price.idx  42752 non-null  float64
 15  cons.conf.idx   42752 non-null  float64
 16  euribor3m       42752 non-null  float64
 17  nr.employed     42752 non-null  int64
 18  y               42752 non-null  object
 19  date            42752 non-null  datetime64[ns]
 20  latitude        42752 non-null  float64
 21  longitude       42752 non-null  float64
 22  id_             42752 non-null  object
dtypes: datetime64[ns](1), float64(6), int64(6), object(10)
memory usage: 7.5+ MB

In [56]:
# ==============================
# 8. CREACION DE VARIABLES
# ==============================
# En este bloque se crean nuevas variables derivadas
# que facilitaran el analisis exploratorio y la interpretacion
# del comportamiento de los clientes.

In [57]:
# ==============================
# 8.1 CREACION DE DURATION_MIN
# ==============================
# Se crea una nueva variable con la duracion
# de la llamada expresada en minutos para facilitar
# la interpretacion del analisis.

df_bank["duration_min"] = (
    df_bank["duration"] / 60
).round(2)

In [58]:
# ==============================
# 8.1 VERIFICACION DE DURATION_MIN
# ==============================
# Se visualizan algunos registros de la nueva variable.

df_bank[
    [
        "duration",
        "duration_min"
    ]
].head()

   duration  duration_min
0       261          4.35
1       149          2.48
2       226          3.77
3       151          2.52
4       307          5.12

In [59]:
# ==============================
# 8.2 CREACION DE CONTACT_YEAR
# ==============================
# Se extrae el año de la fecha de contacto
# para facilitar futuros analisis temporales.

df_bank["contact_year"] = (
    df_bank["date"].dt.year
)

In [60]:
# ==============================
# 8.3 CREACION DE CONTACT_MONTH
# ==============================
# Se extrae el nombre del mes de la fecha
# para analizar patrones temporales mensuales.

df_bank["contact_month"] = (
    df_bank["date"].dt.month_name()
)

In [61]:
# ==============================
# 8.4 ORDENAR VARIABLE CONTACT_MONTH
# ==============================
# Se establece un orden cronologico correcto
# para los meses del año.

orden_meses = [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December"
]

df_bank["contact_month"] = pd.Categorical(
    df_bank["contact_month"],
    categories=orden_meses,
    ordered=True
)

In [62]:
# ==============================
# 8.5 CREACION DE AGE_GROUP
# ==============================
# Se crean grupos de edad para facilitar
# el analisis segmentado de clientes.

bins = [0, 25, 35, 45, 55, 65, 100]

labels = [
    "18-25",
    "26-35",
    "36-45",
    "46-55",
    "56-65",
    "65+"
]

df_bank["age_group"] = pd.cut(
    df_bank["age"],
    bins=bins,
    labels=labels
)

In [63]:
# ==============================
# 8.6 CREACION DE PREVIOUS_CONTACT
# ==============================
# Se crea una variable que indica si el cliente
# habia sido contactado anteriormente.

df_bank["previous_contact"] = np.where(
    df_bank["previous"] > 0,
    "Yes",
    "No"
)

In [64]:
# ==============================
# 8.7 VERIFICACION DE NUEVAS VARIABLES
# ==============================
# Se revisan las nuevas variables creadas.

df_bank[
    [
        "duration_min",
        "contact_year",
        "contact_month",
        "age_group",
        "previous_contact"
    ]
].head()

   duration_min  contact_year contact_month age_group previous_contact
0          4.35          2019        August     36-45               No
1          2.48          2016     September     56-65               No
2          3.77          2019      February     36-45               No
3          2.52          2015      November     36-45               No
4          5.12          2017       January     56-65               No

In [65]:
# ==============================
# 9. UNION DE DATASETS
# ==============================
# En este bloque se unen los datasets df_bank y df_customer.
# La union se realiza mediante el identificador comun:
# - df_bank: id_
# - df_customer: ID
# El objetivo es enriquecer el dataset bancario con informacion
# adicional del cliente.

In [66]:
# ==============================
# 9.1 REVISION DE CLAVES DE UNION
# ==============================
# Se revisan algunos valores de las columnas identificadoras
# para comprobar que ambas pueden utilizarse como clave de union.

print("Primeros ID de df_bank:")
display(df_bank["id_"].head())

print("Primeros ID de df_customer:")
display(df_customer["ID"].head())

Primeros ID de df_bank:

0    089b39d8-e4d0-461b-87d4-814d71e0e079
1    e9d37224-cb6f-4942-98d7-46672963d097
2    3f9f49b5-e410-4948-bf6e-f9244f04918b
3    9991fafb-4447-451a-8be2-b0df6098d13e
4    eca60b76-70b6-4077-80ba-bc52e8ebb0eb
Name: id_, dtype: object

Primeros ID de df_customer:

0    089b39d8-e4d0-461b-87d4-814d71e0e079
1    e9d37224-cb6f-4942-98d7-46672963d097
2    3f9f49b5-e410-4948-bf6e-f9244f04918b
3    9991fafb-4447-451a-8be2-b0df6098d13e
4    eca60b76-70b6-4077-80ba-bc52e8ebb0eb
Name: ID, dtype: object

In [67]:
# ==============================
# 9.2 REVISION DE TIPOS DE LAS CLAVES
# ==============================
# Se comprueba que ambas columnas identificadoras
# tengan el mismo tipo de dato.

print("Tipo de id_ en df_bank:", df_bank["id_"].dtype)
print("Tipo de ID en df_customer:", df_customer["ID"].dtype)

Tipo de id_ en df_bank: object
Tipo de ID en df_customer: object

In [68]:
# ==============================
# 9.3 CONVERSION DE CLAVES A TEXTO
# ==============================
# Se convierten ambas claves a string para asegurar
# que el merge no falle por diferencias de tipo.

df_bank["id_"] = df_bank["id_"].astype(str)

df_customer["ID"] = df_customer["ID"].astype(str)

In [69]:
# ==============================
# 9.4 REVISION DE DUPLICADOS EN LAS CLAVES
# ==============================
# Se revisa si existen identificadores duplicados
# antes de realizar la union.

print("Duplicados en id_ de df_bank:")
print(df_bank["id_"].duplicated().sum())

print("\nDuplicados en ID de df_customer:")
print(df_customer["ID"].duplicated().sum())

Duplicados en id_ de df_bank:
0

Duplicados en ID de df_customer:
0

In [70]:
# ==============================
# 9.5 REVISION DE COINCIDENCIAS ENTRE DATASETS
# ==============================
# Se calcula cuantos registros de df_bank tienen coincidencia
# con df_customer mediante el identificador.

coincidencias = df_bank["id_"].isin(df_customer["ID"]).sum()

print("Registros de df_bank con coincidencia en df_customer:")
print(coincidencias)

print("\nPorcentaje de coincidencia:")
print(round(coincidencias / len(df_bank) * 100, 2))

Registros de df_bank con coincidencia en df_customer:
42752

Porcentaje de coincidencia:
100.0

In [71]:
# ==============================
# 9.6 UNION DE DATASETS
# ==============================
# Se realiza un left join para conservar todos los registros
# del dataset bancario y anadir la informacion disponible
# del dataset de clientes.

df_final = df_bank.merge(
    df_customer,
    how="left",
    left_on="id_",
    right_on="ID"
)

In [72]:
# ==============================
# 9.7 VERIFICACION DE DIMENSIONES TRAS LA UNION
# ==============================
# Se comparan las dimensiones antes y despues del merge
# para comprobar que la union se ha realizado correctamente.

print("Shape df_bank:", df_bank.shape)
print("Shape df_customer:", df_customer.shape)
print("Shape df_final:", df_final.shape)

Shape df_bank: (42752, 28)
Shape df_customer: (43170, 6)
Shape df_final: (42752, 34)

In [73]:
# ==============================
# 9.8 REVISION DE NULOS TRAS LA UNION
# ==============================
# Se revisan posibles valores nulos generados tras el merge

df_final.isnull().sum()

age                  0
job                  0
marital              0
education            0
default              0
housing              0
loan                 0
contact              0
duration             0
campaign             0
pdays                0
previous             0
poutcome             0
emp.var.rate         0
cons.price.idx       0
cons.conf.idx        0
euribor3m            0
nr.employed          0
y                    0
date                 0
latitude             0
longitude            0
id_                  0
duration_min         0
contact_year         0
contact_month        0
age_group            0
previous_contact     0
Income               0
Kidhome              0
Teenhome             0
Dt_Customer          0
NumWebVisitsMonth    0
ID                   0
dtype: int64

In [74]:
# ==============================
# 9.9 REVISION DE COLUMNAS DEL DATASET FINAL
# ==============================
# Se revisan las columnas disponibles tras unir ambos datasets.

df_final.columns

Index(['age', 'job', 'marital', 'education', 'default', 'housing', 'loan',
       'contact', 'duration', 'campaign', 'pdays', 'previous', 'poutcome',
       'emp.var.rate', 'cons.price.idx', 'cons.conf.idx', 'euribor3m',
       'nr.employed', 'y', 'date', 'latitude', 'longitude', 'id_',
       'duration_min', 'contact_year', 'contact_month', 'age_group',
       'previous_contact', 'Income', 'Kidhome', 'Teenhome', 'Dt_Customer',
       'NumWebVisitsMonth', 'ID'],
      dtype='object')

In [75]:
# ==============================
# 9.10 VISUALIZACION DEL DATASET FINAL
# ==============================
# Se visualizan las primeras filas del dataframe final.

df_final.head()

,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,id_,duration_min,contact_year,contact_month,age_group,previous_contact,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
0,38,housemaid,MARRIED,basic.4y,No,No,No,telephone,261,1,999,0,NONEXISTENT,1.10,93.99,-36.40,4.86,5191,no,2019-08-02,41.49,-71.23,089b39d8-e4d0-461b-87d4-814d71e0e079,4.35,2019,August,36-45,No,161770,1,0,2012-04-04,29,089b39d8-e4d0-461b-87d4-814d71e0e079
1,57,services,MARRIED,high.school,unknown,No,No,telephone,149,1,999,0,NONEXISTENT,1.10,93.99,-36.40,4.86,5191,no,2016-09-14,34.60,-83.92,e9d37224-cb6f-4942-98d7-46672963d097,2.48,2016,September,56-65,No,85477,1,1,2012-12-30,7,e9d37224-cb6f-4942-98d7-46672963d097
2,37,services,MARRIED,high.school,No,Yes,No,telephone,226,1,999,0,NONEXISTENT,1.10,93.99,-36.40,4.86,5191,no,2019-02-15,34.94,-94.85,3f9f49b5-e410-4948-bf6e-f9244f04918b,3.77,2019,February,36-45,No,147233,1,1,2012-02-02,5,3f9f49b5-e410-4948-bf6e-f9244f04918b
3,40,admin.,MARRIED,basic.6y,No,No,No,telephone,151,1,999,0,NONEXISTENT,1.10,93.99,-36.40,4.86,5191,no,2015-11-29,49.04,-70.31,9991fafb-4447-451a-8be2-b0df6098d13e,2.52,2015,November,36-45,No,121393,1,2,2012-12-21,29,9991fafb-4447-451a-8be2-b0df6098d13e
4,56,services,MARRIED,high.school,No,No,Yes,telephone,307,1,999,0,NONEXISTENT,1.10,93.99,-36.40,4.86,5191,no,2017-01-29,38.03,-104.46,eca60b76-70b6-4077-80ba-bc52e8ebb0eb,5.12,2017,January,56-65,No,63164,1,2,2012-06-20,20,eca60b76-70b6-4077-80ba-bc52e8ebb0eb

In [76]:
# ==============================
# 9.11 CREACION DE CUSTOMER_SENIORITY_DAYS
# ==============================
# Se calcula la antiguedad del cliente en dias
# desde su fecha de alta hasta la fecha
# de la campaña de marketing.

df_final["customer_seniority_days"] = (
    df_final["date"] - df_final["Dt_Customer"]
).dt.days

In [77]:
# ==============================
# 8.X CREACION DE CUSTOMER_SENIORITY_YEARS
# ==============================
# Se calcula la antiguedad aproximada del cliente
# en años para facilitar la interpretacion.

df_final["customer_seniority_years"] = (
    df_final["customer_seniority_days"] / 365
).round(1)

In [78]:
# ==============================
# 8.X CREACION DE CUSTOMER_YEAR
# ==============================
# Se extrae el año en el que el cliente
# se dio de alta en la empresa.

df_final["customer_year"] = (
    df_final["Dt_Customer"].dt.year
)

In [79]:
# ==============================
# 8.X CREACION DE CUSTOMER_MONTH
# ==============================
# Se extrae el mes de alta del cliente.

df_final["customer_month"] = (
    df_final["Dt_Customer"].dt.month_name()
)

In [80]:
# ==============================
# 10. EXPORTACION DE DATOS LIMPIOS
# ==============================
# En este bloque se exporta el dataset final limpio
# para su posterior uso en el analisis exploratorio
# y visualizacion de datos.

In [81]:
# ==============================
# 10.1 REVISION FINAL DEL DATASET
# ==============================
# Se revisa la estructura final del dataframe
# antes de exportarlo.

df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42752 entries, 0 to 42751
Data columns (total 38 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   age                       42752 non-null  int64
 1   job                       42752 non-null  object
 2   marital                   42752 non-null  object
 3   education                 42752 non-null  object
 4   default                   42752 non-null  object
 5   housing                   42752 non-null  object
 6   loan                      42752 non-null  object
 7   contact                   42752 non-null  object
 8   duration                  42752 non-null  int64
 9   campaign                  42752 non-null  int64
 10  pdays                     42752 non-null  int64
 11  previous                  42752 non-null  int64
 12  poutcome                  42752 non-null  object
 13  emp.var.rate              42752 non-null  float64
 14  cons.price.idx            42752 non-null  float64
 15  cons.conf.idx             42752 non-null  float64
 16  euribor3m                 42752 non-null  float64
 17  nr.employed               42752 non-null  int64
 18  y                         42752 non-null  object
 19  date                      42752 non-null  datetime64[ns]
 20  latitude                  42752 non-null  float64
 21  longitude                 42752 non-null  float64
 22  id_                       42752 non-null  object
 23  duration_min              42752 non-null  float64
 24  contact_year              42752 non-null  int32
 25  contact_month             42752 non-null  category
 26  age_group                 42752 non-null  category
 27  previous_contact          42752 non-null  object
 28  Income                    42752 non-null  int64
 29  Kidhome                   42752 non-null  int64
 30  Teenhome                  42752 non-null  int64
 31  Dt_Customer               42752 non-null  datetime64[ns]
 32  NumWebVisitsMonth         42752 non-null  int64
 33  ID                        42752 non-null  object
 34  customer_seniority_days   42752 non-null  int64
 35  customer_seniority_years  42752 non-null  float64
 36  customer_year             42752 non-null  int32
 37  customer_month            42752 non-null  object
dtypes: category(2), datetime64[ns](2), float64(8), int32(2), int64(11), object(13)
memory usage: 11.5+ MB

In [82]:
# ==============================
# 10.2 REVISION FINAL DE NULOS
# ==============================
# Se comprueba que no existan valores nulos
# pendientes antes de guardar el dataset.

df_final.isnull().sum()

age                         0
job                         0
marital                     0
education                   0
default                     0
housing                     0
loan                        0
contact                     0
duration                    0
campaign                    0
pdays                       0
previous                    0
poutcome                    0
emp.var.rate                0
cons.price.idx              0
cons.conf.idx               0
euribor3m                   0
nr.employed                 0
y                           0
date                        0
latitude                    0
longitude                   0
id_                         0
duration_min                0
contact_year                0
contact_month               0
age_group                   0
previous_contact            0
Income                      0
Kidhome                     0
Teenhome                    0
Dt_Customer                 0
NumWebVisitsMonth           0
ID                          0
customer_seniority_days     0
customer_seniority_years    0
customer_year               0
customer_month              0
dtype: int64

In [83]:
# ==============================
# 10.3 REVISION FINAL DE DUPLICADOS
# ==============================
# Se revisa si existen registros duplicados
# en el dataset final.

df_final.duplicated().sum()

np.int64(0)

In [84]:
# ==============================
# 10.4 CREACION DE CARPETA DE EXPORTACION
# ==============================
# Se crea la carpeta donde se almacenaran
# los datos limpios si no existe previamente.

import os

os.makedirs(
    "../datos/datos_transformados",
    exist_ok=True
)

In [85]:
# ==============================
# 10.5 EXPORTACION A CSV
# ==============================
# Se exporta el dataset limpio en formato CSV
# para facilitar su reutilizacion.

df_final.to_csv(
    "../datos/datos_transformados/bank_marketing_clean.csv",
    index=False
)

In [86]:
# ==============================
# 10.6 EXPORTACION A PICKLE
# ==============================
# Se exporta tambien el dataset en formato Pickle,
# permitiendo una carga mas rapida en futuros notebooks.

df_final.to_pickle(
    "../datos/datos_transformados/bank_marketing_clean.pkl"
)

In [87]:
# ==============================
# 10.7 CONFIRMACION DE EXPORTACION
# ==============================
# Se muestra un mensaje confirmando
# que la exportacion se realizo correctamente.

print("Dataset limpio exportado correctamente.")

Dataset limpio exportado correctamente.

In [88]:
# ==============================
# 10.8 DIMENSION FINAL DEL DATASET
# ==============================
# Se muestran las dimensiones finales
# del dataset limpio.

print("Shape final del dataset:")

print(df_final.shape)

Shape final del dataset:
(42752, 38)

In [89]:
df_final.head()

,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,id_,duration_min,contact_year,contact_month,age_group,previous_contact,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID,customer_seniority_days,customer_seniority_years,customer_year,customer_month
0,38,housemaid,MARRIED,basic.4y,No,No,No,telephone,261,1,999,0,NONEXISTENT,1.10,93.99,-36.40,4.86,5191,no,2019-08-02,41.49,-71.23,089b39d8-e4d0-461b-87d4-814d71e0e079,4.35,2019,August,36-45,No,161770,1,0,2012-04-04,29,089b39d8-e4d0-461b-87d4-814d71e0e079,2676,7.30,2012,April
1,57,services,MARRIED,high.school,unknown,No,No,telephone,149,1,999,0,NONEXISTENT,1.10,93.99,-36.40,4.86,5191,no,2016-09-14,34.60,-83.92,e9d37224-cb6f-4942-98d7-46672963d097,2.48,2016,September,56-65,No,85477,1,1,2012-12-30,7,e9d37224-cb6f-4942-98d7-46672963d097,1354,3.70,2012,December
2,37,services,MARRIED,high.school,No,Yes,No,telephone,226,1,999,0,NONEXISTENT,1.10,93.99,-36.40,4.86,5191,no,2019-02-15,34.94,-94.85,3f9f49b5-e410-4948-bf6e-f9244f04918b,3.77,2019,February,36-45,No,147233,1,1,2012-02-02,5,3f9f49b5-e410-4948-bf6e-f9244f04918b,2570,7.00,2012,February
3,40,admin.,MARRIED,basic.6y,No,No,No,telephone,151,1,999,0,NONEXISTENT,1.10,93.99,-36.40,4.86,5191,no,2015-11-29,49.04,-70.31,9991fafb-4447-451a-8be2-b0df6098d13e,2.52,2015,November,36-45,No,121393,1,2,2012-12-21,29,9991fafb-4447-451a-8be2-b0df6098d13e,1073,2.90,2012,December
4,56,services,MARRIED,high.school,No,No,Yes,telephone,307,1,999,0,NONEXISTENT,1.10,93.99,-36.40,4.86,5191,no,2017-01-29,38.03,-104.46,eca60b76-70b6-4077-80ba-bc52e8ebb0eb,5.12,2017,January,56-65,No,63164,1,2,2012-06-20,20,eca60b76-70b6-4077-80ba-bc52e8ebb0eb,1684,4.60,2012,June